# Generated by Django 2.0.7 on 2018-08-09 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180808_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='type_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blogtype', to='blog.BlogType'),
        ),
    ]
