# Generated by Django 2.0.7 on 2018-08-09 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180809_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='type_name',
            new_name='blog_type',
        ),
    ]
